fix prettier,eslintand husky config and refined the project

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,33 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm tsc --noEmit && pnpm eslint . && pnpm prettier --write .
+echo 'Running Git Hooks'
+
+echo "🔎 Checking validity of types with TypeScript"
+
+pnpm type-check || (
+    "\n⛔️ There is a type error in the code, fix it, and try commit again. ⛔️";
+    false;
+    )
+
+
+echo "\n✅ No TypeError found"
+echo "\n🔎 Running linter.."
+
+pnpm lint || (
+    echo '\n⛔️ There is a problem in the code. ⌛️ I run linter autofix for you.';
+
+    echo '\n🔎 Running linter autofix..'
+    pnpm lint:fix || (
+      echo '\n⛔️ Autofix failed. Please fix the linting errors manually. ⛔️';
+      false;
+    )
+
+    echo '\n🧐 Please check the changes and commit again.\n'
+    false;
+    )
+
+echo '✅ No Eslint error found'
+echo '⌛️ Running lint staged and git commit ⌛️'
+
+npx lint-staged
